title: Patriotic Parrots
email: pp@parrots.com
description: >-
  Patriotic Paroots are a placeholder for how the blog would look like!
baseurl: "/jekyll-blog"
url: ""
twitter_username: pp
github_username:  pp

plugins:
  - jekyll-feed
